// {
  //             id: 2493,
  //             name: "iPhone 13",
  //             description: "Clean iPhone 13 for your enjoyment",
  //             price: 566.23,
  //             quantity: 1
  //         }
//   const cartProduct = {
//     asin: product.asin,
//     title: product.title,
//     price: product.price && product.price.value,
//     image: product.image,
//     link: product.link,
//     quantity: 1
// };
export const ProductsModul = [
  {
    alt: "product-1",
    asin: "B09JFC967X",
    title: "Apple iPhone 12 Pro, 128GB, Gold - Unlocked (Renewed Premium)",
    link: "https://www.amazon.com/Apple-iPhone-12-Pro-128GB/dp/B09JFC967X/ref=sr_1_7?keywords=iphone+12&qid=1642309501&sr=8-7",
    description: "Apple iPhone 12 Pro, 128GB, Gold - Unlocked (Renewed Premium)",
    id: "B09JFC967X",
    name: "Apple iPhone 12 Pro, 128GB, Gold - Unlocked (Renewed Premium)",
    image: "https://m.media-amazon.com/images/I/711PvTS05pL._AC_SX679_.jpg",
    discount: 12,
    price: 888.34,
  },
  {
    alt: "product-2",
    asin: "B08BHHSB6M",
    title: "Apple iPhone 11 Pro, 64GB, Midnight Green - Unlocked (Renewed Premium)",
    link: "https://www.amazon.com/Apple-iPhone-64GB-Midnight-Green/dp/B08BHHSB6M/ref=sr_1_6?keywords=iphone%2B12&qid=1642309501&sr=8-6&th=1",
    id: "B08BHHSB6M",
    name: "Apple iPhone 11 Pro, 64GB, Midnight Green - Unlocked (Renewed Premium)",
    description: "Apple iPhone 11 Pro, 64GB, Midnight Green - Unlocked (Renewed Premium)",
    discount: 10,
    image: "https://m.media-amazon.com/images/I/81AaNJqE+wS._AC_SY679_.jpg",
    price: 585.00,
  },
  {
    asin: "B08BHFGJXF",
    title: "Apple iPhone 11 Pro Max, 256GB, Midnight Green - Unlocked (Renewed Premium)",
    link: "https://www.amazon.com/Apple-iPhone-256GB-Midnight-Green/dp/B08BHFGJXF/ref=sr_1_5?keywords=iphone%2B12&qid=1642309501&sr=8-5&th=1",
    id: "B08BHFGJXF",
    alt: "product-3",
    name: "Apple iPhone 11 Pro Max, 256GB, Midnight Green - Unlocked (Renewed Premium)",
    description: "Apple iPhone 11 Pro Max, 256GB, Midnight Green - Unlocked (Renewed Premium)",
    discount: 20,
    image: "https://m.media-amazon.com/images/I/71yIGykJFNS._AC_SX679_.jpg",
    price: 739.00,
  },
  {
    asin: "B07ZQRL9XY",
    title: "Apple iPhone 11 Pro, US Version, 256GB, Space Gray - Unlocked (Renewed)",
    link: "https://www.amazon.com/Apple-iPhone-256GB-Unlocked-Renewed/dp/B07ZQRL9XY/ref=sr_1_4?keywords=iphone%2B12&qid=1642309501&sr=8-4&th=1",
    alt: "product-4",
    id: "B07ZQRL9XY",
    name: "Apple iPhone 11 Pro, US Version, 256GB, Space Gray - Unlocked (Renewed)",
    description: "Factory Unlocked Android Cell Phone 128GB US Version Smartphone Pro-Grade",
    discount: 50,
    image: "https://m.media-amazon.com/images/I/81x9I9qXbmL._AC_SY679_.jpg",
    price: 591.99,
  },
  {
    asin: "B08PP5MSVB",
    title: "Apple iPhone 12, 64GB, Black - Fully Unlocked (Renewed)",
    link: "https://www.amazon.com/Apple-iPhone-12-64GB-Black/dp/B08PP5MSVB/ref=sr_1_2?keywords=iphone%2B12&qid=1642309501&sr=8-2&th=1",
    alt: "product-5",
    id: "B08PP5MSVB",
    name: "Apple iPhone 12, 64GB, Black - Fully Unlocked (Renewed)",
    description: "Factory Unlocked Android Cell Phone 128GB US Version Smartphone Pro-Grade",
    discount: 30,
    image: "https://m.media-amazon.com/images/I/715Xkp4KqXL._AC_SY679_.jpg",
    price: 699.99,
  },
  {
    asin: "B09JFP6L1F",
    title: "Apple iPhone 12, 128GB, Blue - Unlocked (Renewed Premium)",
    link: "https://www.amazon.com/Apple-iPhone-12-128GB-Blue/dp/B09JFP6L1F/ref=sr_1_1?keywords=iphone+12&qid=1642309501&sr=8-1",
    alt: "product-6",
    id: "B09JFP6L1F",
    name: "Apple iPhone 12, 128GB, Blue - Unlocked (Renewed Premium)",
    description: "Factory Unlocked Android Cell Phone 128GB US Version Smartphone Pro-Grade",
    discount: 2,
    image: "https://m.media-amazon.com/images/I/7117DN7UkKL._AC_SY679_.jpg",
    price: 788.43,
  },
];
