export const CONNECT_WALLET = "CONNECT_WALLET";
export const DISCONNECT_WALLET = "DISCONNECT_WALLET";
export const ACCOUNT_CHANGE = "ACCOUNT_CHANGE";
export const CHAIN_CHANGE = "CHAIN_CHANGE";
export const NETWORK_CHANGE = "NETWORK_CHANGE";
